const PRODUCT_ACTION = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_SINGLE_PRODUCT: "GET_SINGLE_PRODUCT",
  RE_RENDER_PRODUCT: "RE_RENDER_PRODUCT",
  SEARCH_BAR: "SEARCH_BAR",
  FILTER_PRODUCT: "FILTER_PRODUCT",
};
export default PRODUCT_ACTION;
